options ls = 180 nocenter;
libname ndata "C:\Desktop";
options nocenter ls = 140;
* Importing the DATA;
data NewEngland;
set ndata.NewEngland;
run;
*Manipulating the DATA;
data NewEngland;
set ndata.NewEngland;
if SEX = 1 then Sex2 = "Male";
if SEX = 2 then Sex2 = "Female";
if _AGE_G = 1 then Age = "18-24";
if _AGE_G = 2 then Age = "25-34";
if  3 <= _AGE_G <= 5 then Age = "34-65";
if _AGE_G > 6 then Age = "65+";
if EDUCA <= 1 then Edu = "<= HS";
if EDUCA > 1 then Edu = "> HS";
if INCOME2 <=4 then Inc = "<25k";
if 5 <= INCOME2 <= 6 then Inc = "25-50";
if INCOME2 > 6 then Inc = "50+";
if HLTHPLN1 = 1 then Health = "Yes";
if HLTHPLN1 >= 2 then Health = "No";
run;
* Done out Separately for Diabetes; 
proc surveyfreq data= NewEngland;
table  Sex2 * DIABETE3 /row cl ;
table  Age * DIABETE3 /row cl ;
table  Edu * DIABETE3 /row cl ;
table  Inc * DIABETE3 /row cl ;
table  Health * DIABETE3 /row cl ;
strata _ststr; *do not change;
cluster _psu; *do not change;
weight _LLCPWT;
run;
* Done out Separately for Asthma; 
proc surveyfreq data= NewEngland;
table  Sex2 * ASTHNOW /row cl ;
table  Age * ASTHNOW /row cl ;
table  Edu * ASTHNOW /row cl ;
table  Inc * ASTHNOW /row cl ;
table  Health * ASTHNOW /row cl ;
strata _ststr; *do not change;
cluster _psu; *do not change;
weight _LLCPWT;
run;
* Creating the New Hampshire Dataset;
proc sql;
create table NH as
select * from NewEngland where _STATE = 33;
quit;
* Done out Separately for Diabetes; 
proc surveyfreq data= NH;
table  Sex2 * DIABETE3 /row cl ;
table  Age * DIABETE3 /row cl ;
table  Edu * DIABETE3 /row cl ;
table  Inc * DIABETE3 /row cl ;
table  Health * DIABETE3 /row cl ;
strata _ststr; *do not change;
cluster _psu; *do not change;
weight _LLCPWT;
run;
* Done out Separately for Asthma; 
proc surveyfreq data= NH;
table  Sex2 * ASTHNOW /row cl ;
table  Age * ASTHNOW /row cl ;
table  Edu * ASTHNOW /row cl ;
table  Inc * ASTHNOW /row cl ;
table  Health * ASTHNOW /row cl ;
strata _ststr; *do not change;
cluster _psu; *do not change;
weight _LLCPWT;
run;
