options ls = 180 nocenter;
libname ndata "C:\Desktop";
options nocenter ls = 140;
%Macro Master(a,b);
%do i = 2013 %to 2015;
data NewE&i;
set ndata.Newengland_&i;
run;
data NE&i;
set NewE&i;
length age $50.;
length income $50.;
length education $50.;
length gender $50.;
length asthma $50.;
length diabetes $50.;
length health $50.;
if _ASTHMS1="1" then asthma="Has Asthma";
else if _ASTHMS1="2" or _ASTHMS1="3" then asthma = "Does not have Asthma"; 
else asthma="Unknown to have Asthma";
if DIABETE3="1" then diabetes="Has Diabetes";
else if DIABETE3="2" or DIABETE3="3" or DIABETE3="4" then diabetes="Does not have Diabetes"; 
else diabetes="Unknown to have Diabetes";
if SEX = 1 then Gender = "Male";
else Gender = "Female";
if _AGE_G = 1 then Age = "18-24";
else if _AGE_G = 2 then Age = "25-34";
else if  3 =< _AGE_G =< 5 then Age = "34-65";
else Age="65+";
if EDUCA <= 1 then Education = "<= HS";
else if EDUCA > 1 then Education = "> HS";
else Education="Education Unknown";
if INCOME2 =<4 then Income = "<25k";
else if 5 =< INCOME2 =< 6 then Income = "25-50";
else if INCOME2 > 6 then Income = "50+";
else Income="Income Unknown";
if HLTHPLN1 = 1 then Health = "Yes";
else if HLTHPLN1 >= 2 then Health = "No";
else Health="Health Plan Unknown";
drop _AGE_G INCOME2 EDUCA SEX DIABETE3 ASTHMA3 ASTHNOW _ASTHMS1 _STRWT _RAWRAKE _WT2RAKE;
run;
proc sql;
create table NH&i as
select * from NE&i where _STATE = 33;
quit; 
ods output domain=&a&b&i;
proc surveymeans data=&a&i nobs mean clm sum clsum;
var &b;
strata _ststr; 
cluster _psu;
weight _LLCPWT;
domain Age Gender Education Income Health;
title;
run;
ods trace off;
data FINAL_&a&b&i;
set &a&b&i;
run;
title "&b in &a for &i";
data Out_&a&b&i;
FORMAT Domain_Category $50.;	INFORMAT Domain_Category $50.;
set FINAL_&a&b&i;
if age ^="" then Domain_Category = Age;
else if gender ^="" then Domain_Category = Gender;
else if income ^="" then Domain_Category = Income;
else if health ^="" then Domain_Category = Health;
else Domain_Category = Education;
nlowerclmean = lowerclmean *100;
nupperclmean = upperclmean *100;
percent = MEAN*100;
ciwidth = nupperclmean - nlowerclmean ;
CI= catx(" - ",(put(nlowerclmean ,8.1)),(put(nupperclmean,8.1)));
drop  MEAN DomainLabel VarName	LowerCLSum	StdErr StdDev	UpperCLSum upperclmean lowerclmean Age Gender Income Health Education;
RENAME SUM = WeightedN;
title;
run;
proc export data=out_&a&b&i outfile="C:\Users\Kevin Rossi\Desktop\To-Do\HW2-Health.xlsx" dbms=xlsx replace;
   sheet="&a &b &i";
run;
%end;
%mend Master;

%Master(NE,diabetes);
%Master(NH,diabetes);
%Master(NE,asthma);
%Master(NH,asthma);
